#!/bin/bash

yacc -d yacc_file.y
lex lex_file.l
gcc codegen.c analyser.c y.tab.c lex.yy.c  -o t1
rm y.tab.c lex.yy.c y.tab.h
./t1 $1
exit_code=$?
rm t1

if [ $exit_code -ne 1 ]; then
    lex label_translator.l
    gcc lex.yy.c -o t1
    ./t1
    rm t1 lex.yy.c
fi
